Type: AWS::IAM::Role
Properties:
  RoleName: kinesisStreamToRedshiftRirehoseRole
  AssumeRolePolicyDocument:
    Statement:
    - Effect: Allow
      Principal:
        Service:
        - firehose.amazonaws.com
        - kinesis.amazonaws.com
        - redshift.amazonaws.com
      Action:
      - sts:AssumeRole
  Policies:
  - PolicyName: kinesisStreamToRedshiftRirehosePolicy
    PolicyDocument:
      Statement:
        - Effect: Allow
          Action:
            - kinesis:*
            - s3:AbortMultipartUpload
            - s3:GetBucketLocation
            - s3:GetObject
            - s3:ListBucket
            - s3:ListBucketMultipartUploads
            - s3:PutObject
            - lambda:InvokeFunction
            - lambda:GetFunctionConfiguration
            - logs:PutLogEvents
            - kms:Decrypt
          Resource:
            - "*"
